language: C++
compiler:
  - gcc
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - cmake
      - g++-4.9
      - libboost-dev
before_script:
  - export CXX="g++-4.9"
  - export CC="gcc-4.9"
script:
  - mkdir -p build/release
  - cd build/release
  - cmake -DCMAKE_BUILD_TYPE=Release ../../Source -DPROJECTS_USE_PRECOMPILED_HEADERS=OFF -DBUILD_TESTS=ON -DBUILD_HLSL_PLUGIN=OFF
  - make -j2
  - make test
install: true
branches:
  only:
    - master
    - remove_left_recursion
sudo: false
